// <auto-generated />
using System;
using Angular7NetCoreStore.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angular7NetCoreStore.Infra.Data.Migrations
{
    [DbContext(typeof(Angular7NetCoreStoreContext))]
    [Migration("20190411171120_AddProduct")]
    partial class AddProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Angular7NetCoreStore.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90cac6cb-be67-4aa7-b7b1-20c99dae032d"),
                            BirthDate = new DateTime(1991, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tiago.avila09@gmail.com",
                            Name = "Tiago Aparecido de Ávila",
                            PhoneNumber = "(35)99218-3713"
                        });
                });

            modelBuilder.Entity("Angular7NetCoreStore.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Price");

                    b.Property<decimal>("QuantityOnHand");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac85d7b6-8844-4bb1-b687-45249929497c"),
                            Description = "Guitarra Ibanex GRG220 Preta",
                            Image = "https://http2.mlstatic.com/guitarra-electrica-ibanez-gio-grg220dex-D_NQ_NP_760329-MLV27359093213_052018-F.jpg",
                            Price = 1200m,
                            QuantityOnHand = 50m,
                            Title = "Guitarra Ibanex GRG220"
                        },
                        new
                        {
                            Id = new Guid("12a0652b-2a19-42e0-928c-635413be9211"),
                            Description = "Samsung s9",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh_iIgH_ErtqFO1tiMpysB3Z5VeJUjaThLCtKkajwXA_V4GXkp",
                            Price = 2000m,
                            QuantityOnHand = 50m,
                            Title = "Celular S9"
                        },
                        new
                        {
                            Id = new Guid("ef4383a1-3721-422b-a90a-8c5f86943e7b"),
                            Description = "Kindle new generation",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHmy5pzaQxrs4nzLNXP0Ca-1zkBgzfLCwOMjxmDFDx02FGSzI6",
                            Price = 200m,
                            QuantityOnHand = 50m,
                            Title = "Kindle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
